language: node_js
node_js:
- '9.7'
before_install:
- openssl aes-256-cbc -K $encrypted_7eb6418aecec_key -iv $encrypted_7eb6418aecec_iv
  -in id_rsa.enc -out ~/.ssh/id_rsa -d
- chmod 600 ~/.ssh/id_rsa
- echo -e "Host 120.79.78.132\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
after_success:
- ssh root@120.79.78.132 'cd ~/leafer/meow/ && ./meow.sh'
