language: node_js
node_js:
- '9.7'
before_install:
- openssl aes-256-cbc -K $encrypted_447c0be6f25d_key -iv $encrypted_447c0be6f25d_iv
  -in id_rsa.enc -out C:\\Users\\LEAFERx\\.ssh\\id_rsa -d
after_success:
- ssh root@120.79.78.132:22 'cd ~/leafer/meow/ && pkill -9 node && git pull && npm install && HUBOT_BEARYCHAT_TOKENS=3a7fb71fce149f73d2606e6981a2005e PORT=80 setsid bin/hubot -a bearychat'
